#!/bin/bash
printf "export INSTALL_PHP7=${INSTALL_PHP7:-1}\n"
printf "export INSTALL_PAGESPEED=${INSTALL_PAGESPEED:-1}\n"
printf "export INSTALL_COMPOSER=${INSTALL_COMPOSER:-1}\n"
printf "export INSTALL_BROTLI=${INSTALL_BROTLI:-1}\n"
printf "export USE_OPCACHE_OPTIMIZATION=${USE_OPCACHE_OPTIMIZATION:-1}\n"
printf "export WORKDIR=${WORKDIR:-/var/www/html}\n"
printf "export LANGUAGE=${LANGUAGE:-de_DE.UTF-8}\n"
printf "export TIMEZONE=${TIMEZONE:-Europe/Berlin}\n"
printf "export DOWNLOAD_APP_BUILD_FROM=${DOWNLOAD_APP_BUILD_FROM:-0}\n"
printf "export DOWNLOAD_APP_RUN_FROM=${DOWNLOAD_APP_RUN_FROM:-0}\n"
printf "export COPY_EMPTY_WWW=${COPY_EMPTY_WWW:-0}\n"
printf "export SETUP_FOR_PRODUCTION=${SETUP_FOR_PRODUCTION:-1}\n"
printf "export KLAMBT_WEBSERVER_PRODUCTION=${KLAMBT_WEBSERVER_PRODUCTION:-1}\n"
printf "export INSTALL_GEM=${INSTALL_GEM:-1}\n"